In [4]:
import numpy as np

In [27]:
def inv(a):
    return a.getI()
def pM(a,e):
    return a**e

In [31]:
c = np.matrix([[2,-1],[-1,1]])
t = np.matrix([[5,0],[0,4]])
d = inv(c)*t*t*t*c
d2 = np.matrix([[1,0],[2,-1]])
#print(d)
print(pM(d2,5))

[[ 1  0]
 [ 2 -1]]


In [38]:
a= np.matrix([[-1,-3],[1.7,0.8]])
print(a)
b = np.matrix([0,1])
print(b)
c= np.matrix([1,0])
print(c)
d= np.matrix([[1,0],[0,1]])
print(d)

[[-1.  -3. ]
 [ 1.7  0.8]]
[[0 1]]
[[1 0]]
[[1 0]
 [0 1]]


In [41]:
a*b.T

matrix([[-3. ],
        [ 0.8]])

In [42]:
a*c.T

matrix([[-1. ],
        [ 1.7]])

In [43]:
a*d

matrix([[-1. , -3. ],
        [ 1.7,  0.8]])