In [1]:
import numpy as np

In [18]:
def inv(a):
    return a.getI()
def pM(a,e):
    return a**e
def eigen(M):
    vals, vecs = np.linalg.eig(M)
    return vals,vecs

In [39]:
c = np.matrix([[2,-1],[-1,1]])
t = np.matrix([[5,0],[0,4]])
d = inv(c)*t*t*t*c
d2 = np.matrix([[4,-5,6],
                [7,-8,6],
                [3/2,-1/2,-2]
               ])

eVal,eVec=eigen(d2)

print(pM(d2,2))

[[-10.   17.  -18. ]
 [-19.   26.  -18. ]
 [ -0.5  -2.5  10. ]]


In [40]:
print(eVal)

[ 1. -4. -3.]


In [41]:
print(eVec)

[[-0.6882472  -0.66666667  0.40824829]
 [-0.6882472  -0.66666667 -0.40824829]
 [-0.22941573  0.33333333 -0.81649658]]


In [35]:
print(eVal[0]*eVec[0])
print(eVal[1]*eVec[1])

print(d2@eVec)

[[1.75232997 1.10224347]]
[[-0.04605025  0.10810386]]
[[ 1.75232997  0.07913752]
 [-0.64139729  0.10810386]]


In [49]:
d2 = np.matrix([[0,1,0,0],
                [1,0,0,0],
                [0,0,0,1],
                [0,0,1,0]
               ])
eVal,eVec=eigen(d2)
print(np.around(eVec, decimals=3))
print(np.around(eVal, decimals=3))

[[ 0.707 -0.707  0.     0.   ]
 [ 0.707  0.707  0.     0.   ]
 [ 0.     0.     0.707 -0.707]
 [ 0.     0.     0.707  0.707]]
[ 1. -1.  1. -1.]


In [43]:
a*d

matrix([[-1. , -3. ],
        [ 1.7,  0.8]])